dataset_path: ../../../dataset
feature_type: waveform
platform: VR
pid: null
target_hz: 12hz
workers: 24
warmup_steps: 50
total_steps: 10000
batch_size: 8
world_size: 1
lr: 5.0e-05
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 10
cos: true
epochs: 151
best_tr: 0.4943181872367859
best_val: 0.5757575631141663
