dataset_path: ../../../dataset
feature_type: waveform
platform: VR
pid: P04
target_hz: 10hz
workers: 8
warmup_steps: 50
epochs: 30
batch_size: 4
world_size: 1
lr: 0.0001
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 10
cos: true
total_steps: 2
best_tr: 0.75
best_val: 0.4166666567325592
