dataset_path: ../../../dataset
feature_type: waveform
platform: Sc
pid: null
target_hz: 10hz
workers: 24
warmup_steps: 50
total_steps: 10000
batch_size: 8
world_size: 1
lr: 5.0e-05
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 10
cos: true
epochs: 151
best_tr: 0.638257622718811
best_val: 0.5757575631141663
