dataset_path: ../../../dataset
feature_type: waveform
platform: VR
pid: null
target_hz: all
workers: 8
warmup_steps: 50
epochs: 50
batch_size: 4
world_size: 1
lr: 0.0001
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 10
cos: true
total_steps: 0
best_tr: 0.852623462677002
best_val: 0.6574074029922485
