dataset_path: ../../../dataset
feature_type: waveform
platform: Sc
pid: P17
target_hz: all
workers: 8
warmup_steps: 50
epochs: 30
batch_size: 4
world_size: 1
lr: 0.0001
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 10
cos: true
total_steps: 0
best_tr: 0.8680555820465088
best_val: 0.5
