dataset_path: ../../../dataset
feature_type: waveform
platform: VR
pid: P06
target_hz: all
workers: 24
warmup_steps: 50
total_steps: 500
batch_size: 8
world_size: 1
lr: 5.0e-05
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 10
cos: true
epochs: 27
best_tr: 0.756944477558136
best_val: 0.6944444179534912
