dataset_path: ../../../dataset
feature_type: waveform
platform: VR
pid: null
target_hz: 7hz
workers: 24
warmup_steps: 50
total_steps: 10000
batch_size: 8
world_size: 1
lr: 5.0e-05
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 10
cos: true
epochs: 151
best_tr: 0.6363636255264282
best_val: 0.6212121248245239
