dataset_path: ../../../dataset
feature_type: waveform
platform: VR
pid: P08
target_hz: 10hz
workers: 24
warmup_steps: 1000
total_steps: 10000
batch_size: 8
world_size: 1
lr: 0.0001
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 10
cos: true
epochs: 1666
best_val: 1.0
best_tr: 0.8333333730697632
